version: "3.3"
services:
  export-metrics:
    image: "prom/node-exporter:v1.3.1"
    container_name: "node-exporter"
    network_mode: "host"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/host/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/host/rootfs"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|etc)($$|/)"
    restart: "always"

  export-logs:
    image: "grafana/promtail:main"
    container_name: "promtail"
    network_mode: "host"
    volumes:
      - "/tmp:/tmp:rw"
      - "/var/log:/host/var/log:ro"
      - "${PROMTAIL_CONFIG}:/etc/promtail/config.yml"
    environment:
      - "LOKI_IP=${LOKI_IP}"
      - "PROMTAIL_CONFIG=${PROMTAIL_CONFIG}"
    extra_hosts:
      - "loki:${LOKI_IP}"
    command:
      - "--config.file=/etc/promtail/config.yml"
    restart: "always"

