version: "3.3"
services:
  store-metrics:
    image: "prom/prometheus:latest"
    container_name: "prometheus"
    ports:
      - "9090:9090"
    expose: 
      - "9090"
    environment:
      - "EXPORTER_IP=${EXPORTER_IP}"
      - "PROMETHEUS_CONFIG=${PROMETHEUS_CONFIG}"
    volumes:
      - "${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml"
      - "metrics_storage:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: "always"

  store-logs:
    image: "grafana/loki:latest"
    container_name: "loki"
    ports:
      - "9080:9080"
    expose:
      - "9080"
    environment:
      - "LOKI_CONFIG=${LOKI_CONFIG}"
      - "PROMTAIL_IP=${PROMTAIL_IP}"
    volumes:
      - "logs_storage:/tmp/loki:rw"
      - "${LOKI_CONFIG}:/etc/loki/local-config.yaml"
    restart: "always"
volumes:
  metrics_storage:
  logs_storage:
